// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/mock.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_proto_mock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{0}
}

func (x *DisconnectRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type WrongProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrongProtocolRequest) Reset() {
	*x = WrongProtocolRequest{}
	mi := &file_proto_mock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrongProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrongProtocolRequest) ProtoMessage() {}

func (x *WrongProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrongProtocolRequest.ProtoReflect.Descriptor instead.
func (*WrongProtocolRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{1}
}

func (x *WrongProtocolRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_mock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{2}
}

func (x *ResetRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type ResetStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // Message sequence number
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`          // Payload data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetStreamResponse) Reset() {
	*x = ResetStreamResponse{}
	mi := &file_proto_mock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetStreamResponse) ProtoMessage() {}

func (x *ResetStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetStreamResponse.ProtoReflect.Descriptor instead.
func (*ResetStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{3}
}

func (x *ResetStreamResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ResetStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_mock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{4}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_mock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_mock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *StatusResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayRequest) Reset() {
	*x = DelayRequest{}
	mi := &file_proto_mock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayRequest) ProtoMessage() {}

func (x *DelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayRequest.ProtoReflect.Descriptor instead.
func (*DelayRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{7}
}

func (x *DelayRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type DelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	DelayedMs     int32                  `protobuf:"varint,2,opt,name=delayed_ms,json=delayedMs,proto3" json:"delayed_ms,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayResponse) Reset() {
	*x = DelayResponse{}
	mi := &file_proto_mock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayResponse) ProtoMessage() {}

func (x *DelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayResponse.ProtoReflect.Descriptor instead.
func (*DelayResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{8}
}

func (x *DelayResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DelayResponse) GetDelayedMs() int32 {
	if x != nil {
		return x.DelayedMs
	}
	return 0
}

func (x *DelayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mock_proto protoreflect.FileDescriptor

const file_proto_mock_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mock.proto\x12\x04mock\"7\n" +
	"\x11DisconnectRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\":\n" +
	"\x14WrongProtocolRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"2\n" +
	"\fResetRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"E\n" +
	"\x13ResetStreamResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\a\n" +
	"\x05Empty\"#\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"e\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\fDelayRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"b\n" +
	"\rDelayResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"delayed_ms\x18\x02 \x01(\x05R\tdelayedMs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xe1\x02\n" +
	"\vMockService\x123\n" +
	"\x06Status\x12\x13.mock.StatusRequest\x1a\x14.mock.StatusResponse\x120\n" +
	"\x05Delay\x12\x12.mock.DelayRequest\x1a\x13.mock.DelayResponse\x122\n" +
	"\n" +
	"Disconnect\x12\x17.mock.DisconnectRequest\x1a\v.mock.Empty\x128\n" +
	"\rWrongProtocol\x12\x1a.mock.WrongProtocolRequest\x1a\v.mock.Empty\x126\n" +
	"\x13ResetBeforeResponse\x12\x12.mock.ResetRequest\x1a\v.mock.Empty\x12E\n" +
	"\x12ResetAfterResponse\x12\x12.mock.ResetRequest\x1a\x19.mock.ResetStreamResponse0\x01B\x16Z\x14mock-go-server/protob\x06proto3"

var (
	file_proto_mock_proto_rawDescOnce sync.Once
	file_proto_mock_proto_rawDescData []byte
)

func file_proto_mock_proto_rawDescGZIP() []byte {
	file_proto_mock_proto_rawDescOnce.Do(func() {
		file_proto_mock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mock_proto_rawDesc), len(file_proto_mock_proto_rawDesc)))
	})
	return file_proto_mock_proto_rawDescData
}

var file_proto_mock_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_mock_proto_goTypes = []any{
	(*DisconnectRequest)(nil),    // 0: mock.DisconnectRequest
	(*WrongProtocolRequest)(nil), // 1: mock.WrongProtocolRequest
	(*ResetRequest)(nil),         // 2: mock.ResetRequest
	(*ResetStreamResponse)(nil),  // 3: mock.ResetStreamResponse
	(*Empty)(nil),                // 4: mock.Empty
	(*StatusRequest)(nil),        // 5: mock.StatusRequest
	(*StatusResponse)(nil),       // 6: mock.StatusResponse
	(*DelayRequest)(nil),         // 7: mock.DelayRequest
	(*DelayResponse)(nil),        // 8: mock.DelayResponse
}
var file_proto_mock_proto_depIdxs = []int32{
	5, // 0: mock.MockService.Status:input_type -> mock.StatusRequest
	7, // 1: mock.MockService.Delay:input_type -> mock.DelayRequest
	0, // 2: mock.MockService.Disconnect:input_type -> mock.DisconnectRequest
	1, // 3: mock.MockService.WrongProtocol:input_type -> mock.WrongProtocolRequest
	2, // 4: mock.MockService.ResetBeforeResponse:input_type -> mock.ResetRequest
	2, // 5: mock.MockService.ResetAfterResponse:input_type -> mock.ResetRequest
	6, // 6: mock.MockService.Status:output_type -> mock.StatusResponse
	8, // 7: mock.MockService.Delay:output_type -> mock.DelayResponse
	4, // 8: mock.MockService.Disconnect:output_type -> mock.Empty
	4, // 9: mock.MockService.WrongProtocol:output_type -> mock.Empty
	4, // 10: mock.MockService.ResetBeforeResponse:output_type -> mock.Empty
	3, // 11: mock.MockService.ResetAfterResponse:output_type -> mock.ResetStreamResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mock_proto_init() }
func file_proto_mock_proto_init() {
	if File_proto_mock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mock_proto_rawDesc), len(file_proto_mock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mock_proto_goTypes,
		DependencyIndexes: file_proto_mock_proto_depIdxs,
		MessageInfos:      file_proto_mock_proto_msgTypes,
	}.Build()
	File_proto_mock_proto = out.File
	file_proto_mock_proto_goTypes = nil
	file_proto_mock_proto_depIdxs = nil
}
