// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/mock.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MockService_Status_FullMethodName              = "/mock.MockService/Status"
	MockService_Delay_FullMethodName               = "/mock.MockService/Delay"
	MockService_Disconnect_FullMethodName          = "/mock.MockService/Disconnect"
	MockService_WrongProtocol_FullMethodName       = "/mock.MockService/WrongProtocol"
	MockService_ResetBeforeResponse_FullMethodName = "/mock.MockService/ResetBeforeResponse"
	MockService_ResetAfterResponse_FullMethodName  = "/mock.MockService/ResetAfterResponse"
)

// MockServiceClient is the client API for MockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockServiceClient interface {
	// Return specific status code
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Delay response
	Delay(ctx context.Context, in *DelayRequest, opts ...grpc.CallOption) (*DelayResponse, error)
	// Server closes connection after delay
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Empty, error)
	// Server sends wrong protocol data after delay
	WrongProtocol(ctx context.Context, in *WrongProtocolRequest, opts ...grpc.CallOption) (*Empty, error)
	// Server sends RST before response after delay
	ResetBeforeResponse(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Empty, error)
	// Server sends dummy data, then RST
	ResetAfterResponse(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResetStreamResponse], error)
}

type mockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMockServiceClient(cc grpc.ClientConnInterface) MockServiceClient {
	return &mockServiceClient{cc}
}

func (c *mockServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MockService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockServiceClient) Delay(ctx context.Context, in *DelayRequest, opts ...grpc.CallOption) (*DelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelayResponse)
	err := c.cc.Invoke(ctx, MockService_Delay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MockService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockServiceClient) WrongProtocol(ctx context.Context, in *WrongProtocolRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MockService_WrongProtocol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockServiceClient) ResetBeforeResponse(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MockService_ResetBeforeResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockServiceClient) ResetAfterResponse(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResetStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MockService_ServiceDesc.Streams[0], MockService_ResetAfterResponse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResetRequest, ResetStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MockService_ResetAfterResponseClient = grpc.ServerStreamingClient[ResetStreamResponse]

// MockServiceServer is the server API for MockService service.
// All implementations must embed UnimplementedMockServiceServer
// for forward compatibility.
type MockServiceServer interface {
	// Return specific status code
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Delay response
	Delay(context.Context, *DelayRequest) (*DelayResponse, error)
	// Server closes connection after delay
	Disconnect(context.Context, *DisconnectRequest) (*Empty, error)
	// Server sends wrong protocol data after delay
	WrongProtocol(context.Context, *WrongProtocolRequest) (*Empty, error)
	// Server sends RST before response after delay
	ResetBeforeResponse(context.Context, *ResetRequest) (*Empty, error)
	// Server sends dummy data, then RST
	ResetAfterResponse(*ResetRequest, grpc.ServerStreamingServer[ResetStreamResponse]) error
	mustEmbedUnimplementedMockServiceServer()
}

// UnimplementedMockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMockServiceServer struct{}

func (UnimplementedMockServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMockServiceServer) Delay(context.Context, *DelayRequest) (*DelayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delay not implemented")
}
func (UnimplementedMockServiceServer) Disconnect(context.Context, *DisconnectRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedMockServiceServer) WrongProtocol(context.Context, *WrongProtocolRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WrongProtocol not implemented")
}
func (UnimplementedMockServiceServer) ResetBeforeResponse(context.Context, *ResetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetBeforeResponse not implemented")
}
func (UnimplementedMockServiceServer) ResetAfterResponse(*ResetRequest, grpc.ServerStreamingServer[ResetStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ResetAfterResponse not implemented")
}
func (UnimplementedMockServiceServer) mustEmbedUnimplementedMockServiceServer() {}
func (UnimplementedMockServiceServer) testEmbeddedByValue()                     {}

// UnsafeMockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockServiceServer will
// result in compilation errors.
type UnsafeMockServiceServer interface {
	mustEmbedUnimplementedMockServiceServer()
}

func RegisterMockServiceServer(s grpc.ServiceRegistrar, srv MockServiceServer) {
	// If the following call panics, it indicates UnimplementedMockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MockService_ServiceDesc, srv)
}

func _MockService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockService_Delay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).Delay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockService_Delay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).Delay(ctx, req.(*DelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockService_WrongProtocol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WrongProtocolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).WrongProtocol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockService_WrongProtocol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).WrongProtocol(ctx, req.(*WrongProtocolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockService_ResetBeforeResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).ResetBeforeResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockService_ResetBeforeResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).ResetBeforeResponse(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockService_ResetAfterResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MockServiceServer).ResetAfterResponse(m, &grpc.GenericServerStream[ResetRequest, ResetStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MockService_ResetAfterResponseServer = grpc.ServerStreamingServer[ResetStreamResponse]

// MockService_ServiceDesc is the grpc.ServiceDesc for MockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mock.MockService",
	HandlerType: (*MockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MockService_Status_Handler,
		},
		{
			MethodName: "Delay",
			Handler:    _MockService_Delay_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _MockService_Disconnect_Handler,
		},
		{
			MethodName: "WrongProtocol",
			Handler:    _MockService_WrongProtocol_Handler,
		},
		{
			MethodName: "ResetBeforeResponse",
			Handler:    _MockService_ResetBeforeResponse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ResetAfterResponse",
			Handler:       _MockService_ResetAfterResponse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mock.proto",
}
