// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/mock.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_mock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{0}
}

func (x *CloseRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type CloseStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStreamResponse) Reset() {
	*x = CloseStreamResponse{}
	mi := &file_proto_mock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStreamResponse) ProtoMessage() {}

func (x *CloseStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStreamResponse.ProtoReflect.Descriptor instead.
func (*CloseStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{1}
}

func (x *CloseStreamResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CloseStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WrongProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrongProtocolRequest) Reset() {
	*x = WrongProtocolRequest{}
	mi := &file_proto_mock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrongProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrongProtocolRequest) ProtoMessage() {}

func (x *WrongProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrongProtocolRequest.ProtoReflect.Descriptor instead.
func (*WrongProtocolRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{2}
}

func (x *WrongProtocolRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_mock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{3}
}

func (x *ResetRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type ResetStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // Message sequence number
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`          // Payload data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetStreamResponse) Reset() {
	*x = ResetStreamResponse{}
	mi := &file_proto_mock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetStreamResponse) ProtoMessage() {}

func (x *ResetStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetStreamResponse.ProtoReflect.Descriptor instead.
func (*ResetStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{4}
}

func (x *ResetStreamResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ResetStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_mock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{5}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_proto_mock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{6}
}

func (x *VersionResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_mock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{7}
}

func (x *StatusRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_mock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *StatusResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayRequest) Reset() {
	*x = DelayRequest{}
	mi := &file_proto_mock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayRequest) ProtoMessage() {}

func (x *DelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayRequest.ProtoReflect.Descriptor instead.
func (*DelayRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{9}
}

func (x *DelayRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type DelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	DelayedMs     int32                  `protobuf:"varint,2,opt,name=delayed_ms,json=delayedMs,proto3" json:"delayed_ms,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayResponse) Reset() {
	*x = DelayResponse{}
	mi := &file_proto_mock_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayResponse) ProtoMessage() {}

func (x *DelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayResponse.ProtoReflect.Descriptor instead.
func (*DelayResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{10}
}

func (x *DelayResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DelayResponse) GetDelayedMs() int32 {
	if x != nil {
		return x.DelayedMs
	}
	return 0
}

func (x *DelayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mock_proto protoreflect.FileDescriptor

const file_proto_mock_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mock.proto\x12\x04mock\"2\n" +
	"\fCloseRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"E\n" +
	"\x13CloseStreamResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\":\n" +
	"\x14WrongProtocolRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"2\n" +
	"\fResetRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"E\n" +
	"\x13ResetStreamResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\a\n" +
	"\x05Empty\"E\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"#\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"e\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\fDelayRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"b\n" +
	"\rDelayResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"delayed_ms\x18\x02 \x01(\x05R\tdelayedMs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xdb\x03\n" +
	"\vMockService\x12-\n" +
	"\aVersion\x12\v.mock.Empty\x1a\x15.mock.VersionResponse\x123\n" +
	"\x06Status\x12\x13.mock.StatusRequest\x1a\x14.mock.StatusResponse\x120\n" +
	"\x05Delay\x12\x12.mock.DelayRequest\x1a\x13.mock.DelayResponse\x126\n" +
	"\x13CloseBeforeResponse\x12\x12.mock.CloseRequest\x1a\v.mock.Empty\x12E\n" +
	"\x12CloseAfterResponse\x12\x12.mock.CloseRequest\x1a\x19.mock.CloseStreamResponse0\x01\x128\n" +
	"\rWrongProtocol\x12\x1a.mock.WrongProtocolRequest\x1a\v.mock.Empty\x126\n" +
	"\x13ResetBeforeResponse\x12\x12.mock.ResetRequest\x1a\v.mock.Empty\x12E\n" +
	"\x12ResetAfterResponse\x12\x12.mock.ResetRequest\x1a\x19.mock.ResetStreamResponse0\x01B\x16Z\x14mock-go-server/protob\x06proto3"

var (
	file_proto_mock_proto_rawDescOnce sync.Once
	file_proto_mock_proto_rawDescData []byte
)

func file_proto_mock_proto_rawDescGZIP() []byte {
	file_proto_mock_proto_rawDescOnce.Do(func() {
		file_proto_mock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mock_proto_rawDesc), len(file_proto_mock_proto_rawDesc)))
	})
	return file_proto_mock_proto_rawDescData
}

var file_proto_mock_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_mock_proto_goTypes = []any{
	(*CloseRequest)(nil),         // 0: mock.CloseRequest
	(*CloseStreamResponse)(nil),  // 1: mock.CloseStreamResponse
	(*WrongProtocolRequest)(nil), // 2: mock.WrongProtocolRequest
	(*ResetRequest)(nil),         // 3: mock.ResetRequest
	(*ResetStreamResponse)(nil),  // 4: mock.ResetStreamResponse
	(*Empty)(nil),                // 5: mock.Empty
	(*VersionResponse)(nil),      // 6: mock.VersionResponse
	(*StatusRequest)(nil),        // 7: mock.StatusRequest
	(*StatusResponse)(nil),       // 8: mock.StatusResponse
	(*DelayRequest)(nil),         // 9: mock.DelayRequest
	(*DelayResponse)(nil),        // 10: mock.DelayResponse
}
var file_proto_mock_proto_depIdxs = []int32{
	5,  // 0: mock.MockService.Version:input_type -> mock.Empty
	7,  // 1: mock.MockService.Status:input_type -> mock.StatusRequest
	9,  // 2: mock.MockService.Delay:input_type -> mock.DelayRequest
	0,  // 3: mock.MockService.CloseBeforeResponse:input_type -> mock.CloseRequest
	0,  // 4: mock.MockService.CloseAfterResponse:input_type -> mock.CloseRequest
	2,  // 5: mock.MockService.WrongProtocol:input_type -> mock.WrongProtocolRequest
	3,  // 6: mock.MockService.ResetBeforeResponse:input_type -> mock.ResetRequest
	3,  // 7: mock.MockService.ResetAfterResponse:input_type -> mock.ResetRequest
	6,  // 8: mock.MockService.Version:output_type -> mock.VersionResponse
	8,  // 9: mock.MockService.Status:output_type -> mock.StatusResponse
	10, // 10: mock.MockService.Delay:output_type -> mock.DelayResponse
	5,  // 11: mock.MockService.CloseBeforeResponse:output_type -> mock.Empty
	1,  // 12: mock.MockService.CloseAfterResponse:output_type -> mock.CloseStreamResponse
	5,  // 13: mock.MockService.WrongProtocol:output_type -> mock.Empty
	5,  // 14: mock.MockService.ResetBeforeResponse:output_type -> mock.Empty
	4,  // 15: mock.MockService.ResetAfterResponse:output_type -> mock.ResetStreamResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mock_proto_init() }
func file_proto_mock_proto_init() {
	if File_proto_mock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mock_proto_rawDesc), len(file_proto_mock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mock_proto_goTypes,
		DependencyIndexes: file_proto_mock_proto_depIdxs,
		MessageInfos:      file_proto_mock_proto_msgTypes,
	}.Build()
	File_proto_mock_proto = out.File
	file_proto_mock_proto_goTypes = nil
	file_proto_mock_proto_depIdxs = nil
}
