// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/mock.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_proto_mock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{0}
}

func (x *DisconnectRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type WrongProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrongProtocolRequest) Reset() {
	*x = WrongProtocolRequest{}
	mi := &file_proto_mock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrongProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrongProtocolRequest) ProtoMessage() {}

func (x *WrongProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrongProtocolRequest.ProtoReflect.Descriptor instead.
func (*WrongProtocolRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{1}
}

func (x *WrongProtocolRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_mock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_mock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_proto_mock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{4}
}

func (x *ReadyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadyResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_mock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_mock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *StatusResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayRequest) Reset() {
	*x = DelayRequest{}
	mi := &file_proto_mock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayRequest) ProtoMessage() {}

func (x *DelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayRequest.ProtoReflect.Descriptor instead.
func (*DelayRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{7}
}

func (x *DelayRequest) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

type DelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	DelayedMs     int32                  `protobuf:"varint,2,opt,name=delayed_ms,json=delayedMs,proto3" json:"delayed_ms,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayResponse) Reset() {
	*x = DelayResponse{}
	mi := &file_proto_mock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayResponse) ProtoMessage() {}

func (x *DelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayResponse.ProtoReflect.Descriptor instead.
func (*DelayResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{8}
}

func (x *DelayResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DelayResponse) GetDelayedMs() int32 {
	if x != nil {
		return x.DelayedMs
	}
	return 0
}

func (x *DelayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeadersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersResponse) Reset() {
	*x = HeadersResponse{}
	mi := &file_proto_mock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersResponse) ProtoMessage() {}

func (x *HeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersResponse.ProtoReflect.Descriptor instead.
func (*HeadersResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{9}
}

func (x *HeadersResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HeadersResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type LargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeKb        int32                  `protobuf:"varint,1,opt,name=size_kb,json=sizeKb,proto3" json:"size_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeRequest) Reset() {
	*x = LargeRequest{}
	mi := &file_proto_mock_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeRequest) ProtoMessage() {}

func (x *LargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeRequest.ProtoReflect.Descriptor instead.
func (*LargeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{10}
}

func (x *LargeRequest) GetSizeKb() int32 {
	if x != nil {
		return x.SizeKb
	}
	return 0
}

type LargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeResponse) Reset() {
	*x = LargeResponse{}
	mi := &file_proto_mock_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeResponse) ProtoMessage() {}

func (x *LargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeResponse.ProtoReflect.Descriptor instead.
func (*LargeResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{11}
}

func (x *LargeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_proto_mock_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{12}
}

func (x *EchoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_proto_mock_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mock_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_mock_proto_rawDescGZIP(), []int{13}
}

func (x *EchoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_mock_proto protoreflect.FileDescriptor

const file_proto_mock_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mock.proto\x12\x04mock\"7\n" +
	"\x11DisconnectRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\":\n" +
	"\x14WrongProtocolRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"\a\n" +
	"\x05Empty\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"A\n" +
	"\rReadyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"#\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"e\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\fDelayRequest\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"b\n" +
	"\rDelayResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"delayed_ms\x18\x02 \x01(\x05R\tdelayedMs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa5\x01\n" +
	"\x0fHeadersResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12<\n" +
	"\aheaders\x18\x02 \x03(\v2\".mock.HeadersResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\fLargeRequest\x12\x17\n" +
	"\asize_kb\x18\x01 \x01(\x05R\x06sizeKb\"#\n" +
	"\rLargeResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"!\n" +
	"\vEchoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\"\n" +
	"\fEchoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xca\x03\n" +
	"\vMockService\x12+\n" +
	"\x06Health\x12\v.mock.Empty\x1a\x14.mock.HealthResponse\x12)\n" +
	"\x05Ready\x12\v.mock.Empty\x1a\x13.mock.ReadyResponse\x123\n" +
	"\x06Status\x12\x13.mock.StatusRequest\x1a\x14.mock.StatusResponse\x120\n" +
	"\x05Delay\x12\x12.mock.DelayRequest\x1a\x13.mock.DelayResponse\x12-\n" +
	"\aHeaders\x12\v.mock.Empty\x1a\x15.mock.HeadersResponse\x120\n" +
	"\x05Large\x12\x12.mock.LargeRequest\x1a\x13.mock.LargeResponse\x12-\n" +
	"\x04Echo\x12\x11.mock.EchoRequest\x1a\x12.mock.EchoResponse\x122\n" +
	"\n" +
	"Disconnect\x12\x17.mock.DisconnectRequest\x1a\v.mock.Empty\x128\n" +
	"\rWrongProtocol\x12\x1a.mock.WrongProtocolRequest\x1a\v.mock.EmptyB\x16Z\x14mock-go-server/protob\x06proto3"

var (
	file_proto_mock_proto_rawDescOnce sync.Once
	file_proto_mock_proto_rawDescData []byte
)

func file_proto_mock_proto_rawDescGZIP() []byte {
	file_proto_mock_proto_rawDescOnce.Do(func() {
		file_proto_mock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mock_proto_rawDesc), len(file_proto_mock_proto_rawDesc)))
	})
	return file_proto_mock_proto_rawDescData
}

var file_proto_mock_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_mock_proto_goTypes = []any{
	(*DisconnectRequest)(nil),    // 0: mock.DisconnectRequest
	(*WrongProtocolRequest)(nil), // 1: mock.WrongProtocolRequest
	(*Empty)(nil),                // 2: mock.Empty
	(*HealthResponse)(nil),       // 3: mock.HealthResponse
	(*ReadyResponse)(nil),        // 4: mock.ReadyResponse
	(*StatusRequest)(nil),        // 5: mock.StatusRequest
	(*StatusResponse)(nil),       // 6: mock.StatusResponse
	(*DelayRequest)(nil),         // 7: mock.DelayRequest
	(*DelayResponse)(nil),        // 8: mock.DelayResponse
	(*HeadersResponse)(nil),      // 9: mock.HeadersResponse
	(*LargeRequest)(nil),         // 10: mock.LargeRequest
	(*LargeResponse)(nil),        // 11: mock.LargeResponse
	(*EchoRequest)(nil),          // 12: mock.EchoRequest
	(*EchoResponse)(nil),         // 13: mock.EchoResponse
	nil,                          // 14: mock.HeadersResponse.HeadersEntry
}
var file_proto_mock_proto_depIdxs = []int32{
	14, // 0: mock.HeadersResponse.headers:type_name -> mock.HeadersResponse.HeadersEntry
	2,  // 1: mock.MockService.Health:input_type -> mock.Empty
	2,  // 2: mock.MockService.Ready:input_type -> mock.Empty
	5,  // 3: mock.MockService.Status:input_type -> mock.StatusRequest
	7,  // 4: mock.MockService.Delay:input_type -> mock.DelayRequest
	2,  // 5: mock.MockService.Headers:input_type -> mock.Empty
	10, // 6: mock.MockService.Large:input_type -> mock.LargeRequest
	12, // 7: mock.MockService.Echo:input_type -> mock.EchoRequest
	0,  // 8: mock.MockService.Disconnect:input_type -> mock.DisconnectRequest
	1,  // 9: mock.MockService.WrongProtocol:input_type -> mock.WrongProtocolRequest
	3,  // 10: mock.MockService.Health:output_type -> mock.HealthResponse
	4,  // 11: mock.MockService.Ready:output_type -> mock.ReadyResponse
	6,  // 12: mock.MockService.Status:output_type -> mock.StatusResponse
	8,  // 13: mock.MockService.Delay:output_type -> mock.DelayResponse
	9,  // 14: mock.MockService.Headers:output_type -> mock.HeadersResponse
	11, // 15: mock.MockService.Large:output_type -> mock.LargeResponse
	13, // 16: mock.MockService.Echo:output_type -> mock.EchoResponse
	2,  // 17: mock.MockService.Disconnect:output_type -> mock.Empty
	2,  // 18: mock.MockService.WrongProtocol:output_type -> mock.Empty
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mock_proto_init() }
func file_proto_mock_proto_init() {
	if File_proto_mock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mock_proto_rawDesc), len(file_proto_mock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mock_proto_goTypes,
		DependencyIndexes: file_proto_mock_proto_depIdxs,
		MessageInfos:      file_proto_mock_proto_msgTypes,
	}.Build()
	File_proto_mock_proto = out.File
	file_proto_mock_proto_goTypes = nil
	file_proto_mock_proto_depIdxs = nil
}
